import { 
    HorizontalBox
} from "std-widgets.slint";

import {
    LeftPanel, RightPanel
} from "panels.slint";


export component UI inherits Window {
    property <string> output;
    property <string> url: "https://www.pugetsound.edu/university-bulletin";
    property <bool> narrow_by_dept: true;
    property <string> keywords;
    in property <[string]> department_codes: [];

    callback test_url(string);
    callback load_keywords() -> string;
    callback add_dept();
    callback sub_dept();
    callback run(string, string, bool, [string]);

    HorizontalBox {
        LeftPanel {}
        RightPanel {}
    }
}